export const SELECT_ADDRESS = "SELECT_ADDRESS";
export const FETCH_ACTIVITIES = "FETCH_ACTIVITIES";
export const ACTIVITIES_RECEIVED = "ACTIVITIES_RECEIVED";
export const FETCH_ACTIVITY_DETAIL = "FETCH_ACTIVITY_DETAIL";
export const ACTIVITY_DETAIL_RECEIVED = "ACTIVITY_DETAIL_RECEIVED";
export const FETCH_USER_PROFILE = "FETCH_USER_PROFILE";
export const VIEW_USER_PROFILE = "VIEW_USER_PROFILE";
