// export const VIEW_ACTIVITIES_FORM = "VIEW_ACTIVITIES_FORM";
// export const VIEW_ACTIVITY_DETAILS = "VIEW_ACTIVITY_DETAILS";
// export const VIEW_ACTIVITIES = "VIEW_ACTIVITIES";
// export const DISPLAY_MENU = "DISPLAY_MENU";
// export const HIDE_MENU = "HIDE_MENU";
// export const VIEW_NEWS = "VIEW_NEWS";
export const ACTIVITIES_RECEIVED = "ACTIVITIES_RECEIVED";
export const FETCH_ACTIVITIES = "FETCH_ACTIVITIES";
